sudo : required

services:
  - docker

before_install:
  - docker build -t pranay/docker-react -f Dockerfile.dev .  

script:
  - docker run -e CI=true pranay/docker-react npm run test -- --coverage   

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  evn: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-260010222560"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"  
