version: '3'
services:
  web:
    environment: 
      - CHOKIDAR_USEPOLLING=true
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - /wls/node_modules
      - .:/wls
  tests:
    build: 
      context: .
      dockerfile:   Dockerfile.dev
    
    volumes: 
      - /wls/node_modules
      - .:/wls
  
    command:  ["npm", "run", "test"]    
      